#pragma once

// GENERATED by tools/gen_anims.py from the ASCII frame files — edit those
// (or the sources under tools/anim_src/) and regenerate; do not hand-edit.

#include <stdint.h>

typedef struct {
    const char *const *rows;
    uint8_t nrows;
    int8_t lift;  // pixels above the floor baseline
} cat_frame_t;

static const char *const ANIM_ANGRY_F0[] = {
    "............###.",
    ".......####.#s#.",
    "......#wwww##s#.",
    "..#.#.#wwwwws#..",
    ".#p#p#wwwwwws#..",
    ".#wwwwwwwwwws#..",
    ".#wkwkw##wwww#..",
    ".#wwww#..#www#..",
    "..#ww#....#ww#..",
    "...##......##...",
};
static const char *const ANIM_ANGRY_F1[] = {
    "............####",
    ".......####.#ss#",
    "......#wwww##s#.",
    "..#.#.#wwwwws#..",
    ".#p#p#wwwwwws#..",
    ".#wwwwwwwwwws#..",
    "W#wkwkw##wwww#..",
    ".#wwww#..#www#..",
    "W.#ww#....#ww#..",
    "...##......##...",
};
static const char *const ANIM_ANGRY_F2[] = {
    ".......####.####",
    "......#wwww##ss#",
    "......#wwww##s#.",
    "......#wwwwws#..",
    ".#####wwwwwws#..",
    "W#wwwwwwwwwws#..",
    ".#wkwkw##wwww#..",
    "W#wwww#..#www#..",
    "..#ww#....#ww#..",
    "W..##......##...",
};
static const char *const ANIM_ANGRY_F3[] = {
    ".......####.####",
    "......#wwww##ss#",
    "......#wwww##s#.",
    "......#wwwwws#..",
    ".#####wwwwwws#..",
    ".#wwwwwwwwwws#..",
    "W#wkwkw##wwww#..",
    ".#wwww#..#www#..",
    "W.#ww#....#ww#..",
    "...##......##...",
};
static const char *const ANIM_ANGRY_F4[] = {
    "............####",
    ".......####.#ss#",
    "......#wwww##s#.",
    "..#.#.#wwwwws#..",
    ".#p#p#wwwwwws#..",
    ".#wwwwwwwwwws#..",
    "W#wkwkw##wwww#..",
    ".#wwww#..#www#..",
    "W.#ww#....#ww#..",
    "...##......##...",
};
static const char *const ANIM_ANGRY_F5[] = {
    "............###.",
    ".......####.#s#.",
    "......#wwww##s#.",
    "..#.#.#wwwwws#..",
    ".#p#p#wwwwwws#..",
    ".#wwwwwwwwwws#..",
    ".#wkwkw##wwww#..",
    ".#wwww#..#www#..",
    "..#ww#....#ww#..",
    "...##......##...",
};

static const cat_frame_t ANIM_ANGRY[] = {
    {ANIM_ANGRY_F0, 10, 0},
    {ANIM_ANGRY_F1, 10, 0},
    {ANIM_ANGRY_F2, 10, 0},
    {ANIM_ANGRY_F3, 10, 0},
    {ANIM_ANGRY_F4, 10, 0},
    {ANIM_ANGRY_F5, 10, 0},
};
#define ANIM_ANGRY_N 6

static const char *const ANIM_BIG_JUMP_F0[] = {
    ".#...#..........",
    "#p#.#p#.........",
    "#wp##pw#........",
    "#wwwwww#.....##.",
    "#wkwwkw#....#s#.",
    "#wwwwww##...#s#.",
    "#wwwwwwww##.#s#.",
    "#wwwwwwwwww##s#.",
    ".#wwwwwwwwwws#..",
    ".#wwwwwwwwwws#..",
    ".#w##wwwwwwws#..",
    ".#s#.#wwwwwws#..",
    ".##..#########..",
};
static const char *const ANIM_BIG_JUMP_F1[] = {
    ".#...#..........",
    "#p#.#p#.........",
    "#wp##pw#........",
    "#wwwwww#........",
    "#wkwwkw#........",
    "#wwwwww###......",
    "#wwwwwwwww##....",
    ".#wwwwwwwwww###.",
    ".#w#wwwwww#wss#.",
    ".##############.",
};
static const char *const ANIM_BIG_JUMP_F2[] = {
    ".#...#..........",
    "#p#.#p#.........",
    "#wp##pw#........",
    "#wwwwww#........",
    "#wkwwkw#........",
    "#wwwwww#........",
    "#wwwwwwww#......",
    ".#wwwwwww#......",
    ".#wwwwwws#......",
    ".#w##www##......",
    ".#w#.#ww#s#.....",
    ".#w#.#ww##s#....",
    ".#s#.#ss#.#s#...",
    ".##..####..##...",
};
static const char *const ANIM_BIG_JUMP_F3[] = {
    ".#...#..........",
    "#p#.#p#.........",
    "#wp##pw#........",
    "#wwwwww#......##",
    "#wkwwkw#.....#s#",
    "#wwwwww##...#s#.",
    "#wwwwwwww###s#..",
    ".#wwwwwwwwws#...",
    ".#wwwwwwwwww#...",
    ".#w#ww#wwww#....",
    ".##.##.#####....",
};
static const char *const ANIM_BIG_JUMP_F4[] = {
    ".#...#..........",
    "#p#.#p#.........",
    "#wp##pw#........",
    "#wwwwww#........",
    "#wkwwkw#........",
    "#wwwwww#....##..",
    "#wwwwwwww#.#s#..",
    ".#wwwwwww##s#...",
    ".#wwwwwws#s#....",
    ".#w##www####....",
    ".#w#.#ww#.......",
    ".#w#.#ww#.......",
    ".#s#.#ss#.......",
    ".##..####.......",
};
static const char *const ANIM_BIG_JUMP_F5[] = {
    ".#...#..........",
    "#p#.#p#.........",
    "#wp##pw#........",
    "#wwwwww#.....##.",
    "#wkwwkw#....#s#.",
    "#wwwwww###..#s#.",
    "#wwwwwwwww###s#.",
    ".#wwwwwwwwwws#..",
    ".#w#wwwwww#ws#..",
    ".#############..",
};
static const char *const ANIM_BIG_JUMP_F6[] = {
    ".#...#..........",
    "#p#.#p#.........",
    "#wp##pw#........",
    "#wwwwww#.....##.",
    "#wkwwkw#....#s#.",
    "#wwwwww##...#s#.",
    "#wwwwwwww##.#s#.",
    "#wwwwwwwwww##s#.",
    ".#wwwwwwwwwws#..",
    ".#wwwwwwwwwws#..",
    ".#w##wwwwwwws#..",
    ".#s#.#wwwwwws#..",
    ".##..#########..",
};

static const cat_frame_t ANIM_BIG_JUMP[] = {
    {ANIM_BIG_JUMP_F0, 13, 0},
    {ANIM_BIG_JUMP_F1, 10, 0},
    {ANIM_BIG_JUMP_F2, 14, 4},
    {ANIM_BIG_JUMP_F3, 11, 8},
    {ANIM_BIG_JUMP_F4, 14, 4},
    {ANIM_BIG_JUMP_F5, 10, 0},
    {ANIM_BIG_JUMP_F6, 13, 0},
};
#define ANIM_BIG_JUMP_N 7

static const char *const ANIM_CLEAN_EAR_F0[] = {
    ".....#..........",
    "###.#p#.........",
    "#ww##pw#........",
    "#ww#www#........",
    "#w#wwkw#........",
    "#w#wwww###......",
    "#w#wwwwwww#.....",
    "#wwwwwwwwww##...",
    ".#wwwwwwwwww##..",
    ".#wwwwwwwwwws#..",
    ".#s#wwwwwwwss#..",
    ".#s#wwwwwwsss#..",
    ".##.##########..",
};
static const char *const ANIM_CLEAN_EAR_F1[] = {
    "####............",
    "#www##..........",
    "#ww##p#.........",
    "#ww##pw#........",
    "#w#wwww#........",
    "#w#wwkw###......",
    "#w#wwwwwww#.....",
    "#wwwwwwwwww##...",
    ".#wwwwwwwwww##..",
    ".#wwwwwwwwwws#..",
    ".#s#wwwwwwwss#..",
    ".#s#wwwwwwsss#..",
    ".##.##########..",
};
static const char *const ANIM_CLEAN_EAR_F2[] = {
    "................",
    ".#...#..........",
    "#p#.#p#.........",
    "#wp##pw#........",
    "###wwww#........",
    "#ww#wkw###......",
    "#ww#wwwwww#.....",
    "#wwwwwwwwww##...",
    ".#wwwwwwwwww##..",
    ".#wwwwwwwwwws#..",
    ".#s#wwwwwwwss#..",
    ".#s#wwwwwwsss#..",
    ".##.##########..",
};
static const char *const ANIM_CLEAN_EAR_F3[] = {
    ".#...#..........",
    "#p#.#p#.........",
    "#####pw#........",
    "#ww#www#........",
    "#ww#wkw#........",
    "#w#wwww###......",
    "#w#wwwwwww#.....",
    "#wwwwwwwwww##...",
    ".#wwwwwwwwww##..",
    ".#wwwwwwwwwws#..",
    ".#s#wwwwwwwss#..",
    ".#s#wwwwwwsss#..",
    ".##.##########..",
};

static const cat_frame_t ANIM_CLEAN_EAR[] = {
    {ANIM_CLEAN_EAR_F0, 13, 0},
    {ANIM_CLEAN_EAR_F1, 13, 0},
    {ANIM_CLEAN_EAR_F2, 13, 0},
    {ANIM_CLEAN_EAR_F3, 13, 0},
};
#define ANIM_CLEAN_EAR_N 4

static const char *const ANIM_CLEAN_PAW_F0[] = {
    "..#...#.........",
    ".#p#.#p#........",
    ".#wp##pw#.......",
    ".#wwwwww#.......",
    ".#wkwwkw#.......",
    ".#wwwwww#.......",
    "#w#wwwww#.......",
    "#w#wwwwww##.....",
    "#w#wwwwwwws#....",
    ".#wwwwwwwwww##..",
    ".#w#wwwwwwwws#..",
    ".#w#.#wwwwwws#..",
    ".#s#.#wwwwwss#..",
    ".##..########...",
};
static const char *const ANIM_CLEAN_PAW_F1[] = {
    "..#...#.........",
    ".#p#.#p#........",
    ".#wp##pw#.......",
    ".#wwwwww#.......",
    ".#w^ww^w#.......",
    "#wwwwwww#.......",
    "#w#wwwwww##.....",
    "#w#wwwwwwws#....",
    ".#wwwwwwwwww##..",
    ".#w#wwwwwwwws#..",
    ".#w#.#wwwwwws#..",
    ".#s#.#wwwwwss#..",
    ".##..########...",
};
static const char *const ANIM_CLEAN_PAW_F2[] = {
    "..#...#.........",
    ".#p#.#p#........",
    ".#wp##pw#.......",
    ".#wwwwww#.......",
    ".#wkwwkw#.......",
    ".#wwwwww#.......",
    ".#wwwwww#.......",
    ".#wwwwwww##.....",
    "#w#wwwwwwws#....",
    "#w#wwwwwwwww##..",
    ".#w#wwwwwwwws#..",
    ".#w#.#wwwwwws#..",
    ".#s#.#wwwwwss#..",
    ".##..########...",
};
static const char *const ANIM_CLEAN_PAW_F3[] = {
    "..##..#.........",
    ".#p#.#p#........",
    ".#wp##pw#.......",
    ".#wwwwww#.......",
    ".#wkwwkw#.......",
    ".#wwwwww#.......",
    "#w#wwwww#.......",
    "#w#wwwwww##.....",
    "#w#wwwwwwws#....",
    ".#wwwwwwwwww##..",
    ".#w#wwwwwwwws#..",
    ".#w#.#wwwwwws#..",
    ".#s#.#wwwwwss#..",
    ".##..########...",
};

static const cat_frame_t ANIM_CLEAN_PAW[] = {
    {ANIM_CLEAN_PAW_F0, 14, 0},
    {ANIM_CLEAN_PAW_F1, 13, 0},
    {ANIM_CLEAN_PAW_F2, 14, 0},
    {ANIM_CLEAN_PAW_F3, 14, 0},
};
#define ANIM_CLEAN_PAW_N 4

static const char *const ANIM_LEAP_F0[] = {
    ".#...#..........",
    "#p#.#p#.........",
    "#wp##pw#........",
    "#wwwwww#....####",
    "#wkwwkw#..##wws#",
    "#wwwwww###wws###",
    ".#wwwwwwwwww#...",
    ".#wwwwwwwwww#...",
    ".#w#wwwwww#w#...",
    ".##.######.##...",
};
static const char *const ANIM_LEAP_F1[] = {
    ".#...#..........",
    "#p#.#p#.........",
    "#wp##pw#........",
    "#wwwwww#....####",
    "#wkwwkw#..##wws#",
    "#wwwwww###wws###",
    "#wwwwwwwwwww#...",
    ".#wwwwwwwwww#...",
    ".#w######wwww#..",
    ".##.....#wws#...",
    ".........#ws#...",
    ".........####...",
};
static const char *const ANIM_LEAP_F2[] = {
    ".#...#..........",
    "#p#.#p#.........",
    "#wp##pw#........",
    "#wwwwww#....####",
    "#wkwwkw#..##wws#",
    "#wwwwww###wws###",
    "#wwwwwwwwwwwww#.",
    ".#wwwwwwwwwwww#.",
    "#ww#######wws#..",
    "###.......####..",
};
static const char *const ANIM_LEAP_F3[] = {
    ".#...#..........",
    "#p#.#p#.........",
    "#wp##pw#........",
    "#wwwwww#....####",
    "#wkwwkw#..##wws#",
    "#wwwwww###wws###",
    ".#wwwwwwwwww#...",
    ".#w#wwww#www#...",
    ".############...",
};
static const char *const ANIM_LEAP_F4[] = {
    ".#...#..........",
    "#p#.#p#.........",
    "#wp##pw#........",
    "#wwwwww#....####",
    "#wkwwkw#..##wws#",
    "#wwwwww###wws###",
    ".#wwwwwwwwww#...",
    ".#wwwwwwwwww#...",
    ".#w######www#...",
    ".#w#....####....",
    ".##.............",
};
static const char *const ANIM_LEAP_F5[] = {
    ".#...#..........",
    "#p#.#p#.........",
    "#wp##pw#........",
    "#wwwwww#....####",
    "#wkwwkw#..##wws#",
    "#wwwwww###wws###",
    ".#wwwwwwwwww#...",
    ".#wwwwwwwwww#...",
    ".#w#####www#....",
    ".#w#...####.....",
    ".##.............",
};
static const char *const ANIM_LEAP_F6[] = {
    ".#...#..........",
    "#p#.#p#.........",
    "#wp##pw#........",
    "#wwwwww#....####",
    "#wkwwkw#..##wws#",
    "#wwwwww###wws###",
    ".#wwwwwwwww#....",
    ".#wwwwwwwww#....",
    ".#w#ww##ww##....",
    ".#w#.#ww#.#w#...",
    ".#s#.#ss#.#s#...",
    ".##..####..##...",
};

static const cat_frame_t ANIM_LEAP[] = {
    {ANIM_LEAP_F0, 10, 0},
    {ANIM_LEAP_F1, 12, 2},
    {ANIM_LEAP_F2, 10, 5},
    {ANIM_LEAP_F3, 9, 6},
    {ANIM_LEAP_F4, 11, 3},
    {ANIM_LEAP_F5, 11, 0},
    {ANIM_LEAP_F6, 12, 0},
};
#define ANIM_LEAP_N 7

static const char *const ANIM_PAWING_F0[] = {
    "....#...#.......",
    "...#p#.#p#..###.",
    "...#wp##pw#.#s#.",
    "...#wwwwww#.#w#.",
    "...#wkwwkw#.#w#.",
    "...#wwwwww###w#.",
    "....#wwwwwwwww#.",
    "....#wwwwwwwww#.",
    "....#w#ww##ww##.",
    "....#w#.#ss#.#w#",
    "....##..####..##",
};
static const char *const ANIM_PAWING_F1[] = {
    "....#...#.......",
    "...#p#.#p#..###.",
    "...#wp##pw#.#s#.",
    "...#wwwwww#.#w#.",
    "...#wkwwkw#.#w#.",
    "...#wwwwww###w#.",
    "..###wwwwwwwww#.",
    "..#wwwwwwwwwww#.",
    "...##w#ww##ww##.",
    "........#ss#.#w#",
    "........####..##",
};
static const char *const ANIM_PAWING_F2[] = {
    "....#...#.......",
    "...#p#.#p#..###.",
    "...#wp##pw#.#s#.",
    "...#wwwwww#.#w#.",
    "...#wkwwkw#.#w#.",
    "...#wwwwww###w#.",
    ".####wwwwwwwww#.",
    "#wwwwwwwwwwwww#.",
    ".####w#ww##ww##.",
    "........#ss#.#w#",
    "........####..##",
};
static const char *const ANIM_PAWING_F3[] = {
    "....#...#.......",
    "...#p#.#p#..###.",
    "...#wp##pw#.#s#.",
    "...#wwwwww#.#w#.",
    "...#wkwwkw#.#w#.",
    "...#wwwwww###w#.",
    "....#wwwwwwwww#.",
    "..###wwwwwwwww#.",
    "..#www#ww##ww##.",
    ".#w##...#ss#.#w#",
    ".##.....####..##",
};
static const char *const ANIM_PAWING_F4[] = {
    "....#...#.......",
    "...#p#.#p#..###.",
    "...#wp##pw#.#s#.",
    "...#wwwwww#.#w#.",
    "...#wkwwkw#.#w#.",
    "...#wwwwww###w#.",
    "....#wwwwwwwww#.",
    "....#wwwwwwwww#.",
    "...#ww#ww##ww##.",
    "...#w#..#ss#.#w#",
    "...##...####..##",
};
static const char *const ANIM_PAWING_F5[] = {
    "....#...#.......",
    "...#p#.#p#..###.",
    "...#wp##pw#.#s#.",
    "...#wwwwww#.#w#.",
    "...#wkwwkw#.#w#.",
    "...#wwwwww###w#.",
    "....#wwwwwwwww#.",
    "....#wwwwwwwww#.",
    "....#w#ww##ww##.",
    "....#w#.#ss#.#w#",
    "....##..####..##",
};

static const cat_frame_t ANIM_PAWING[] = {
    {ANIM_PAWING_F0, 11, 0},
    {ANIM_PAWING_F1, 11, 0},
    {ANIM_PAWING_F2, 11, 0},
    {ANIM_PAWING_F3, 11, 0},
    {ANIM_PAWING_F4, 11, 0},
    {ANIM_PAWING_F5, 11, 0},
};
#define ANIM_PAWING_N 6

static const char *const ANIM_PORTRAIT_TAIL_F0[] = {
    "....#...#.......",
    "...#p#.#p#......",
    "...#wp##pw#.....",
    "...#wwwwww#.....",
    "...#wkwwkw#.....",
    "...#wwwwww#.....",
    "..#wwwwwwww#....",
    "..#wwwwwwww#....",
    ".#wwwwwwwwww#...",
    ".#wwwwwwwwww####",
    ".#w#wwwwww#w#ws#",
    ".#s#ww##ww#s#ws#",
    ".###############",
};
static const char *const ANIM_PORTRAIT_TAIL_F1[] = {
    "....#...#.......",
    "...#p#.#p#......",
    "...#wp##pw#.....",
    "...#wwwwww#.....",
    "...#wkwwkw#.....",
    "...#wwwwww#.....",
    "..#wwwwwwww#....",
    "..#wwwwwwww#####",
    ".#wwwwwwwwww#ws#",
    ".#wwwwwwwwww#ws#",
    ".#w#wwwwww#w#ws#",
    ".#s#ww##ww#s#ws#",
    ".###############",
};
static const char *const ANIM_PORTRAIT_TAIL_F2[] = {
    "....#....#......",
    "...#p#..#p#.....",
    "...#wp##pw#.....",
    "...#wwwwww#.....",
    "...#wkwwkw#.....",
    "...#wwwwww#.....",
    "..#wwwwwwww#....",
    "..#wwwwwwww#....",
    ".#wwwwwwwwww#...",
    ".#wwwwwwwwww####",
    ".#w#wwwwww#w#ws#",
    ".#s#ww##ww#s#ws#",
    ".###############",
};
static const char *const ANIM_PORTRAIT_TAIL_F3[] = {
    "....#...#.......",
    "...#p#.#p#......",
    "...#wp##pw#.....",
    "...#wwwwww#.....",
    "...#wkwwkw#.....",
    "...#wwwwww#.....",
    "..#wwwwwwww#....",
    "..#wwwwwwww#....",
    ".#wwwwwwwwww#...",
    ".#wwwwwwwwww#...",
    ".#w#wwwwww#w####",
    ".#s#ww##ww#s#ws#",
    ".###############",
};

static const cat_frame_t ANIM_PORTRAIT_TAIL[] = {
    {ANIM_PORTRAIT_TAIL_F0, 13, 0},
    {ANIM_PORTRAIT_TAIL_F1, 13, 0},
    {ANIM_PORTRAIT_TAIL_F2, 13, 0},
    {ANIM_PORTRAIT_TAIL_F3, 13, 0},
};
#define ANIM_PORTRAIT_TAIL_N 4

static const char *const ANIM_PROFILE_TAIL_F0[] = {
    ".#...#..........",
    "#p#.#p#.........",
    "#wp##pw#........",
    "#wwwwww#........",
    "#wkwwkw#........",
    "#wwwwww#........",
    ".#wwww###.......",
    ".#wwwwwww#......",
    ".#wwwwwwws#.....",
    ".#wwwwwwwws#....",
    ".#w###wwwws####.",
    ".#w#.#wwwws#wws#",
    ".##..###########",
};
static const char *const ANIM_PROFILE_TAIL_F1[] = {
    ".#...#..........",
    "#p#.#p#.........",
    "#wp##pw#........",
    "#wwwwww#........",
    "#wkwwkw#........",
    "#wwwwww#........",
    ".#wwww###.......",
    ".#wwwwwww#......",
    ".#wwwwwwws#.....",
    ".#wwwwwwwws#..##",
    ".#w###wwwws###s#",
    ".#w#.#wwwws#ww#.",
    ".##..#########..",
};
static const char *const ANIM_PROFILE_TAIL_F2[] = {
    ".#...#..........",
    "#p#.#p#.........",
    "#wp##pw#........",
    "#wwwwww#........",
    "#wkwwkw#........",
    "#wwwwww#........",
    ".#wwww###.......",
    ".#wwwwwww#......",
    ".#wwwwwwws#...##",
    ".#wwwwwwwws#.#s#",
    ".#w###wwwws###w#",
    ".#w#.#wwwws#ww#.",
    ".##..#########..",
};
static const char *const ANIM_PROFILE_TAIL_F3[] = {
    ".#...#..........",
    "#p#.#p#.........",
    "#wp##pw#........",
    "#wwwwww#........",
    "#wkwwkw#........",
    "#wwwwww#........",
    ".#wwww###.......",
    ".#wwwwwww#......",
    ".#wwwwwwws#.....",
    ".#wwwwwwwws#..##",
    ".#w###wwwws###s#",
    ".#w#.#wwwws#ww#.",
    ".##..#########..",
};

static const cat_frame_t ANIM_PROFILE_TAIL[] = {
    {ANIM_PROFILE_TAIL_F0, 13, 0},
    {ANIM_PROFILE_TAIL_F1, 13, 0},
    {ANIM_PROFILE_TAIL_F2, 13, 0},
    {ANIM_PROFILE_TAIL_F3, 13, 0},
};
#define ANIM_PROFILE_TAIL_N 4

static const char *const ANIM_SLEEP_F0[] = {
    "................",
    "........####....",
    "...#..##wwww##..",
    "..#p##p#wwwwww#.",
    ".#wwwwwwwwwwww#.",
    ".#w^^wwwswwwww#.",
    "#wwwwwwswwwwww#.",
    "#kwwwwswwwwwww#.",
    "#ss#wwwwwwwwws#.",
    "#ss#wwwwwwwwss#.",
    "#ss#sssssssss#..",
    ".############...",
};
static const char *const ANIM_SLEEP_F1[] = {
    "........####....",
    ".......#wwww##..",
    "...#..##wwwwww#.",
    "..#p##p#wwwwww#.",
    ".#wwwwwwwwwwww#.",
    ".#w^^wwwswwwww#.",
    "#wwwwwwswwwwww#.",
    "#kwwwwswwwwwww#.",
    "#ss#wwwwwwwwws#.",
    "#ss#wwwwwwwwss#.",
    "#ss#sssssssss#..",
    ".############...",
};
static const char *const ANIM_SLEEP_F2[] = {
    "........####....",
    ".......#wwww##..",
    "...#..##wwwwww#.",
    "..#p##p#wwwwww#.",
    ".#wwwwwwwwwwww#.",
    ".#w^^wwwswwwww#.",
    "#wwwwwwswwwwww#.",
    "#kwwwwswwwwwww#.",
    "#ss#wwwwwwwwws#.",
    "#ss#wwwwwwwwss#.",
    "#ss#sssssssss#..",
    ".############...",
};
static const char *const ANIM_SLEEP_F3[] = {
    "................",
    "........####....",
    "...#..##wwww##..",
    "..#p##p#wwwwww#.",
    ".#wwwwwwwwwwww#.",
    ".#w^^wwwswwwww#.",
    "#wwwwwwswwwwww#.",
    "#kwwwwswwwwwww#.",
    "#ss#wwwwwwwwws#.",
    "#ss#wwwwwwwwss#.",
    "#ss#sssssssss#..",
    ".############...",
};

static const cat_frame_t ANIM_SLEEP[] = {
    {ANIM_SLEEP_F0, 12, 0},
    {ANIM_SLEEP_F1, 12, 0},
    {ANIM_SLEEP_F2, 12, 0},
    {ANIM_SLEEP_F3, 12, 0},
};
#define ANIM_SLEEP_N 4

static const char *const ANIM_TROT_F0[] = {
    ".#...#..........",
    "#p#.#p#.........",
    "#wp##pw#........",
    "#wwwwww#........",
    "#wkwwkw#..######",
    "#wwwwww###wwwws#",
    ".#wwwwwwwww#####",
    ".#wwwwwwwww#....",
    ".##w##ss#w##....",
    ".#w#.#ss##w#....",
    "#s#...##..#s#...",
    "##.........##...",
};
static const char *const ANIM_TROT_F1[] = {
    ".#...#..........",
    "#p#.#p#.........",
    "#wp##pw#........",
    "#wwwwww#........",
    "#wkwwkw#..######",
    "#wwwwww###wwwws#",
    ".#wwwwwwwww#####",
    ".#wwwwwwwww#....",
    ".#w###ss##w#....",
    ".#w#.#ss##w#....",
    ".#s#..##.#s#....",
    ".##.......##....",
};
static const char *const ANIM_TROT_F2[] = {
    ".#...#..........",
    "#p#.#p#.........",
    "#wp##pw#........",
    "#wwwwww#........",
    "#wkwwkw#..######",
    "#wwwwww###wwwws#",
    ".#wwwwwwwww#####",
    ".#wwwwwwwww#....",
    ".##ww####ww#....",
    "..#sw#..#sw#....",
    "...##....##.....",
};
static const char *const ANIM_TROT_F3[] = {
    ".#...#..........",
    "#p#.#p#.........",
    "#wp##pw#........",
    "#wwwwww#........",
    "#wkwwkw#..######",
    "#wwwwww###wwwws#",
    ".#wwwwwwwww#####",
    ".#wwwwwwwww#....",
    ".###s#wws###....",
    "..#s##ww#s#.....",
    ".#s#..##.#s#....",
    ".##.......##....",
};
static const char *const ANIM_TROT_F4[] = {
    ".#...#..........",
    "#p#.#p#.........",
    "#wp##pw#........",
    "#wwwwww#........",
    "#wkwwkw#..######",
    "#wwwwww###wwwws#",
    ".#wwwwwwwww#####",
    ".#wwwwwwwww#....",
    ".##s##ww#s##....",
    "..#s##ww#s#.....",
    "..#s#.###s#.....",
    "..##.....##.....",
};
static const char *const ANIM_TROT_F5[] = {
    ".#...#..........",
    "#p#.#p#.........",
    "#wp##pw#........",
    "#wwwwww#........",
    "#wkwwkw#..######",
    "#wwwwww###wwwws#",
    ".#wwwwwwwww#####",
    ".#wwwwwwwww#....",
    ".##ww####ww#....",
    "..#ws#..#ws#....",
    "...##....##.....",
};

static const cat_frame_t ANIM_TROT[] = {
    {ANIM_TROT_F0, 12, 0},
    {ANIM_TROT_F1, 12, 0},
    {ANIM_TROT_F2, 11, 2},
    {ANIM_TROT_F3, 12, 0},
    {ANIM_TROT_F4, 12, 0},
    {ANIM_TROT_F5, 11, 2},
};
#define ANIM_TROT_N 6

