#!/usr/bin/env python3
"""Bake the side-scrolling world from the background/ panoramas.

Takes the four hand-made time-of-day panoramas (day, dawn, dusk, night),
synthesizes twilight as a 50/50 dusk+night blend, scales everything to the
368-px logical height (block-aligned width), pixelates to 8-px blocks, and
emits main/cat_bg.c as pre-rotated per-world-column strips so the renderer
scrolls with plain row copies.

Usage: gen_world.py background/ main/
"""
import os
import re
import struct
import zlib
import sys

BLOCK = 8
VIEW_H = 368
PANEL_H = 368  # strip length = panel columns

src = open(__file__.replace('gen_world.py', 'gen_bg.py')).read()
src = src.replace("if __name__ == '__main__':\n    main()", "")
src = re.sub(r"\nmain\(\)\s*$", "\n", src)
ns = {}
exec(compile(src, 'gen_bg', 'exec'), ns)
decode_png = ns['decode_png']


def blend(a, b):
    return bytearray((x + y) // 2 for x, y in zip(a, b))


def content_rows(img, w, h):
    """Trim white letterbox margins: the art band is wherever rows stop being
    near-white."""
    def row_white(y):
        n = hit = 0
        for x in range(0, w, 32):
            r, g, b = img[(y * w + x) * 4:(y * w + x) * 4 + 3]
            n += 1
            if r > 245 and g > 245 and b > 245:
                hit += 1
        return hit >= n - 1
    top = 0
    while top < h - 1 and row_white(top):
        top += 1
    bot = h - 1
    while bot > top and row_white(bot):
        bot -= 1
    return top, bot + 1


def bake(img, w, h, world_w):
    # Area-average to the coarse block grid, then expand to hard blocks.
    gw, gh = world_w // BLOCK, VIEW_H // BLOCK
    cells = []
    for oy in range(gh):
        sy0, sy1 = oy * h / gh, (oy + 1) * h / gh
        for ox in range(gw):
            sx0, sx1 = ox * w / gw, (ox + 1) * w / gw
            r = g = b = n = 0
            for yy in range(int(sy0), max(int(sy0) + 1, int(sy1))):
                for xx in range(int(sx0), max(int(sx0) + 1, int(sx1))):
                    i = (min(yy, h - 1) * w + min(xx, w - 1)) * 4
                    r += img[i]; g += img[i + 1]; b += img[i + 2]; n += 1
            r //= n; g //= n; b //= n
            v = ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)
            cells.append(((v >> 8) & 0xFF) | ((v & 0xFF) << 8))
    # Strips: for world column wx, panel px 0..367 shows logical row
    # ly = VIEW_H-1-px at logical x = wx.
    strips = []
    for wx in range(world_w):
        cx = wx // BLOCK
        strip = []
        for px in range(PANEL_H):
            cy = (VIEW_H - 1 - px) // BLOCK
            strip.append(cells[cy * gw + cx])
        strips.append(strip)
    return strips


def main():
    bg_dir, out_dir = sys.argv[1], sys.argv[2]
    day = decode_png(f'{bg_dir}/park.png')
    dawn = decode_png(f'{bg_dir}/dawn.png')
    dusk = decode_png(f'{bg_dir}/dusk.png')
    night = decode_png(f'{bg_dir}/night.png')
    w, h = day[0], day[1]
    for v in (dawn, dusk, night):
        assert (v[0], v[1]) == (w, h), 'panoramas must share dimensions'

    # The art may be letterboxed; crop to the shared content band, then take
    # extra sky off the top so the scenery scales up against the fixed-size
    # cat (measured: ~120 px of pure sky above the treetops).
    SKY_TRIM = 110
    top, bot = content_rows(day[2], w, h)
    top += SKY_TRIM
    ch = bot - top
    print(f'content band: rows {top}..{bot} ({ch} px of {h}, sky trim {SKY_TRIM})')
    cropped = []
    for (vw, vh, img) in (day, dawn, dusk, night):
        cropped.append((vw, ch, img[top * vw * 4:bot * vw * 4]))
    day, dawn, dusk, night = cropped
    h = ch

    world_w = int(round(w * (VIEW_H / h) / BLOCK)) * BLOCK
    twilight = (w, h, blend(dusk[2], night[2]))

    # Order must match the firmware's BG_* indices.
    variants = [('DAY', day), ('DAWN', dawn), ('DUSK', dusk),
                ('TWILIGHT', twilight), ('NIGHT', night)]

    # Three outputs from one bake:
    #   cat_bg.c    the plain arrays the host tools compile against
    #   cat_bg_z.c  the same worlds DEFLATE'd, which is what the firmware
    #               carries — this art is 8x-blocky, so it compresses ~75:1
    #               and all five variants fit in ~130 KB of flash
    #   sd/*.bin    raw strips, for dropping new art on the card by hand
    sd_dir = f'{out_dir}/../sd/pixelcat'
    os.makedirs(sd_dir, exist_ok=True)
    packed = []

    with open(f'{out_dir}/cat_bg.c', 'w') as f:
        f.write('// GENERATED by tools/gen_world.py — do not hand-edit.\n')
        f.write('#include "cat_bg.h"\n\n')
        f.write(f'const uint16_t cat_bg[{len(variants)}][{world_w}][{PANEL_H}] = {{\n')
        for i, (name, (vw, vh, img)) in enumerate(variants):
            strips = bake(img, vw, vh, world_w)
            f.write('{\n')
            for strip in strips:
                f.write('{' + ','.join(f'0x{v:04x}' for v in strip) + '},\n')
            f.write('},\n')
            raw = b''.join(struct.pack(f'<{len(s)}H', *s) for s in strips)
            with open(f'{sd_dir}/world_{i}.bin', 'wb') as b:
                b.write(raw)
            # Raw DEFLATE (no zlib wrapper): the ESP32-S3 ROM's tinfl
            # inflates it for free.
            co = zlib.compressobj(9, zlib.DEFLATED, -15)
            packed.append(co.compress(raw) + co.flush())
            print(f'{name} baked: {len(raw)} -> {len(packed[-1])} bytes '
                  f'({len(raw) / len(packed[-1]):.0f}x)')
        f.write('};\n')

    with open(f'{out_dir}/cat_bg_z.c', 'w') as f:
        f.write('// GENERATED by tools/gen_world.py — do not hand-edit.\n')
        f.write('// The park, DEFLATE\'d. Inflated into PSRAM at run time by\n'
                '// world.c using the ROM\'s tinfl.\n')
        f.write('#include "config.h"\n#if WORLD_FROM_SD\n')
        f.write('#include "cat_bg.h"\n\n')
        for i, blob in enumerate(packed):
            f.write(f'static const uint8_t z{i}[] = {{')
            f.write(','.join(str(b) for b in blob))
            f.write('};\n')
        f.write(f'\nconst uint8_t *const cat_bg_z[{len(packed)}] = {{')
        f.write(','.join(f'z{i}' for i in range(len(packed))))
        f.write('};\n')
        f.write(f'const uint32_t cat_bg_z_len[{len(packed)}] = {{')
        f.write(','.join(str(len(b)) for b in packed))
        f.write('};\n#endif\n')
    print(f'compressed park: {sum(len(b) for b in packed) / 1024:.0f} KB')

    with open(f'{out_dir}/cat_bg.h', 'w') as f:
        f.write('#pragma once\n#include <stdint.h>\n\n')
        f.write(f'#define BG_VARIANTS {len(variants)}\n')
        f.write(f'#define BG_WORLD_W {world_w}\n')
        f.write(f'#define BG_STRIP_H {PANEL_H}\n\n')
        for i, (name, _) in enumerate(variants):
            f.write(f'#define BG_{name} {i}\n')
        f.write('\n// On the device the park is carried DEFLATE\'d and\n'
                '// inflated into PSRAM; the host tools use the plain arrays.\n'
                '// cat_bg_strips() hides which.\n')
        f.write('#if WORLD_FROM_SD\n')
        f.write(f'const uint16_t (*cat_bg_strips(int variant))[{PANEL_H}];\n')
        f.write('extern const uint8_t *const cat_bg_z[BG_VARIANTS];\n')
        f.write('extern const uint32_t cat_bg_z_len[BG_VARIANTS];\n')
        f.write('#else\n')
        f.write(f'extern const uint16_t cat_bg[{len(variants)}][{world_w}][{PANEL_H}];\n')
        f.write(f'static inline const uint16_t (*cat_bg_strips(int variant))[{PANEL_H}]\n')
        f.write('{\n    return cat_bg[variant];\n}\n')
        f.write('#endif\n')
    print(f'world: {world_w} x {VIEW_H} ({world_w // 448:.0f}+ screens), '
          f'{len(variants) * world_w * PANEL_H * 2 / 1e6:.1f} MB in flash')


main()
