#!/usr/bin/env python3
"""Bake the side-scrolling world from the background/ panoramas.

Takes the four hand-made time-of-day panoramas (day, dawn, dusk, night),
synthesizes twilight as a 50/50 dusk+night blend, scales everything to the
368-px logical height (block-aligned width), pixelates to 8-px blocks, and
emits main/cat_bg.c as pre-rotated per-world-column strips so the renderer
scrolls with plain row copies.

Usage: gen_world.py background/ main/
"""
import re
import sys

BLOCK = 8
VIEW_H = 368
PANEL_H = 368  # strip length = panel columns

src = open(__file__.replace('gen_world.py', 'gen_bg.py')).read()
src = src.replace("if __name__ == '__main__':\n    main()", "")
src = re.sub(r"\nmain\(\)\s*$", "\n", src)
ns = {}
exec(compile(src, 'gen_bg', 'exec'), ns)
decode_png = ns['decode_png']


def blend(a, b):
    return bytearray((x + y) // 2 for x, y in zip(a, b))


def content_rows(img, w, h):
    """Trim white letterbox margins: the art band is wherever rows stop being
    near-white."""
    def row_white(y):
        n = hit = 0
        for x in range(0, w, 32):
            r, g, b = img[(y * w + x) * 4:(y * w + x) * 4 + 3]
            n += 1
            if r > 245 and g > 245 and b > 245:
                hit += 1
        return hit >= n - 1
    top = 0
    while top < h - 1 and row_white(top):
        top += 1
    bot = h - 1
    while bot > top and row_white(bot):
        bot -= 1
    return top, bot + 1


def bake(img, w, h, world_w):
    # Area-average to the coarse block grid, then expand to hard blocks.
    gw, gh = world_w // BLOCK, VIEW_H // BLOCK
    cells = []
    for oy in range(gh):
        sy0, sy1 = oy * h / gh, (oy + 1) * h / gh
        for ox in range(gw):
            sx0, sx1 = ox * w / gw, (ox + 1) * w / gw
            r = g = b = n = 0
            for yy in range(int(sy0), max(int(sy0) + 1, int(sy1))):
                for xx in range(int(sx0), max(int(sx0) + 1, int(sx1))):
                    i = (min(yy, h - 1) * w + min(xx, w - 1)) * 4
                    r += img[i]; g += img[i + 1]; b += img[i + 2]; n += 1
            r //= n; g //= n; b //= n
            v = ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)
            cells.append(((v >> 8) & 0xFF) | ((v & 0xFF) << 8))
    # Strips: for world column wx, panel px 0..367 shows logical row
    # ly = VIEW_H-1-px at logical x = wx.
    strips = []
    for wx in range(world_w):
        cx = wx // BLOCK
        strip = []
        for px in range(PANEL_H):
            cy = (VIEW_H - 1 - px) // BLOCK
            strip.append(cells[cy * gw + cx])
        strips.append(strip)
    return strips


def main():
    bg_dir, out_dir = sys.argv[1], sys.argv[2]
    day = decode_png(f'{bg_dir}/park.png')
    dawn = decode_png(f'{bg_dir}/dawn.png')
    dusk = decode_png(f'{bg_dir}/dusk.png')
    night = decode_png(f'{bg_dir}/night.png')
    w, h = day[0], day[1]
    for v in (dawn, dusk, night):
        assert (v[0], v[1]) == (w, h), 'panoramas must share dimensions'

    # The art may be letterboxed; crop to the shared content band.
    top, bot = content_rows(day[2], w, h)
    ch = bot - top
    print(f'content band: rows {top}..{bot} ({ch} px of {h})')
    cropped = []
    for (vw, vh, img) in (day, dawn, dusk, night):
        cropped.append((vw, ch, img[top * vw * 4:bot * vw * 4]))
    day, dawn, dusk, night = cropped
    h = ch

    world_w = int(round(w * (VIEW_H / h) / BLOCK)) * BLOCK
    twilight = (w, h, blend(dusk[2], night[2]))

    # Order must match the firmware's BG_* indices.
    variants = [('DAY', day), ('DAWN', dawn), ('DUSK', dusk),
                ('TWILIGHT', twilight), ('NIGHT', night)]

    with open(f'{out_dir}/cat_bg.c', 'w') as f:
        f.write('// GENERATED by tools/gen_world.py — do not hand-edit.\n')
        f.write('#include "cat_bg.h"\n\n')
        f.write(f'const uint16_t cat_bg[{len(variants)}][{world_w}][{PANEL_H}] = {{\n')
        for name, (vw, vh, img) in variants:
            strips = bake(img, vw, vh, world_w)
            f.write('{\n')
            for strip in strips:
                f.write('{' + ','.join(f'0x{v:04x}' for v in strip) + '},\n')
            f.write('},\n')
            print(f'{name} baked')
        f.write('};\n')

    with open(f'{out_dir}/cat_bg.h', 'w') as f:
        f.write('#pragma once\n#include <stdint.h>\n\n')
        f.write(f'#define BG_VARIANTS {len(variants)}\n')
        f.write(f'#define BG_WORLD_W {world_w}\n')
        f.write(f'#define BG_STRIP_H {PANEL_H}\n\n')
        for i, (name, _) in enumerate(variants):
            f.write(f'#define BG_{name} {i}\n')
        f.write(f'\nextern const uint16_t cat_bg[{len(variants)}][{world_w}][{PANEL_H}];\n')
    print(f'world: {world_w} x {VIEW_H} ({world_w // 448:.0f}+ screens), '
          f'{len(variants) * world_w * PANEL_H * 2 / 1e6:.1f} MB in flash')


main()
