#!/usr/bin/env python3
"""Generate main/cat_anims.h from ASCII animation frame files.

Usage: gen_anims.py <dir-with-anim_*.txt> <out.h>

Each anim_<name>.txt holds frames separated by '---' lines; a frame block may
start with 'lift=N'. Rows must be 16 chars (validated, same rules as
ascii2png.py).
"""
import glob
import os
import sys

SPRITE_W = 16
CHARSET = set('.#wspk^Wrz')


def parse(path):
    frames, cur, lift = [], [], 0
    for line in open(path):
        line = line.rstrip('\n')
        if line.startswith('---'):
            if cur:
                frames.append((cur, lift))
            cur, lift = [], 0
        elif line.startswith('lift='):
            lift = int(line[5:])
        elif line:
            cur.append(line)
    if cur:
        frames.append((cur, lift))
    return frames


def main():
    src_dir, out_path = sys.argv[1], sys.argv[2]
    files = sorted(glob.glob(os.path.join(src_dir, 'anim_*.txt')))
    if not files:
        sys.exit(f'no anim_*.txt in {src_dir}')

    lines = [
        '#pragma once',
        '',
        '// GENERATED by tools/gen_anims.py from the ASCII frame files — edit those',
        '// (or the sources under tools/anim_src/) and regenerate; do not hand-edit.',
        '',
        '#include <stdint.h>',
        '',
        'typedef struct {',
        '    const char *const *rows;',
        '    uint8_t nrows;',
        '    int8_t lift;  // pixels above the floor baseline',
        '} cat_frame_t;',
        '',
    ]

    for path in files:
        name = os.path.basename(path)[5:-4]
        cname = name.upper()
        frames = parse(path)
        for i, (rows, lift) in enumerate(frames):
            for j, r in enumerate(rows):
                if len(r) != SPRITE_W:
                    sys.exit(f'{name} frame {i+1} row {j+1}: {len(r)} chars: {r!r}')
                bad = set(r) - CHARSET
                if bad:
                    sys.exit(f'{name} frame {i+1} row {j+1}: bad chars {bad}')
            lines.append(f'static const char *const ANIM_{cname}_F{i}[] = {{')
            for r in rows:
                lines.append(f'    "{r}",')
            lines.append('};')
        lines.append('')
        lines.append(f'static const cat_frame_t ANIM_{cname}[] = {{')
        for i, (rows, lift) in enumerate(frames):
            lines.append(f'    {{ANIM_{cname}_F{i}, {len(rows)}, {lift}}},')
        lines.append('};')
        lines.append(f'#define ANIM_{cname}_N {len(frames)}')
        lines.append('')
        print(f'{name}: {len(frames)} frames')

    open(out_path, 'w').write('\n'.join(lines) + '\n')
    print(f'wrote {out_path}')


if __name__ == '__main__':
    main()
