#!/usr/bin/env python3
"""Generate main/sun_table.h: sunrise/sunset minutes (PST, UTC-8) for every
day of the year at ZIP 94403 (San Mateo, CA), via the NOAA solar equations.
The firmware adds an hour while US DST is in effect.

Usage: gen_sun.py main
"""
import math
import sys

LAT, LON = 37.538, -122.300  # 94403
TZ = -8.0  # PST

def sun_minutes(doy):
    # NOAA: fractional year (radians), non-leap reference.
    g = 2 * math.pi / 365 * (doy - 1)
    eqtime = 229.18 * (0.000075 + 0.001868*math.cos(g) - 0.032077*math.sin(g)
                       - 0.014615*math.cos(2*g) - 0.040849*math.sin(2*g))
    decl = (0.006918 - 0.399912*math.cos(g) + 0.070257*math.sin(g)
            - 0.006758*math.cos(2*g) + 0.000907*math.sin(2*g)
            - 0.002697*math.cos(3*g) + 0.00148*math.sin(3*g))
    lat = math.radians(LAT)
    zenith = math.radians(90.833)  # official sunrise/sunset
    cos_ha = (math.cos(zenith) / (math.cos(lat) * math.cos(decl))
              - math.tan(lat) * math.tan(decl))
    cos_ha = max(-1.0, min(1.0, cos_ha))
    ha = math.degrees(math.acos(cos_ha))
    noon = 720 - 4 * LON - eqtime + TZ * 60
    rise = noon - 4 * ha
    sets = noon + 4 * ha
    return int(round(rise)), int(round(sets))

def main():
    out = sys.argv[1]
    rises, sets = [], []
    for doy in range(1, 367):
        r, s = sun_minutes(min(doy, 365))
        rises.append(r)
        sets.append(s)
    with open(out + '/sun_table.h', 'w') as f:
        f.write('#pragma once\n\n')
        f.write('// GENERATED by tools/gen_sun.py — sunrise/sunset for 94403\n')
        f.write('// (San Mateo, CA), minutes after midnight PST (UTC-8), indexed\n')
        f.write('// by day of year - 1. Add 60 while US DST is in effect.\n\n')
        f.write('#include <stdint.h>\n\n')
        for name, vals in (('k_sunrise', rises), ('k_sunset', sets)):
            f.write(f'static const uint16_t {name}[366] = {{\n')
            for i in range(0, 366, 12):
                f.write('    ' + ', '.join(str(v) for v in vals[i:i+12]) + ',\n')
            f.write('};\n\n')
    def hm(m):
        return f'{m//60:02d}:{m%60:02d}'
    print(f'winter (day 1): rise {hm(rises[0])} set {hm(sets[0])} PST')
    print(f'summer (day 172): rise {hm(rises[171])} set {hm(sets[171])} PST')
    print('wrote sun_table.h')

main()
